server:
  port: 8081
eureka:
  instance:
    hostname: 192.168.160.1
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:8080/eureka/
spring:
  application:
    name: eureka-client
  datasource:
    username: test
    password: root
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521:orcl
  freemarker:
    suffix: .html
    settings:
      number_format: 0.##

mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
